# Generated by Django 4.2.4 on 2023-08-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlideMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('page_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_slide', to='api.header')),
            ],
        ),
        migrations.CreateModel(
            name='IconMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(null=True, upload_to='icon/')),
                ('page_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icon_slide', to='api.header')),
            ],
        ),
    ]
