# Generated by Django 4.2.4 on 2023-08-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconmain',
            name='page_data',
        ),
        migrations.RemoveField(
            model_name='slidemain',
            name='page_data',
        ),
        migrations.AddField(
            model_name='iconmain',
            name='page_data',
            field=models.ManyToManyField(related_name='icon_slide', to='api.header'),
        ),
        migrations.AddField(
            model_name='slidemain',
            name='page_data',
            field=models.ManyToManyField(related_name='main_slide', to='api.header'),
        ),
    ]
