# Generated by Django 4.2.4 on 2023-08-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_iconmain_page_data_remove_slidemain_page_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconmain',
            name='header_logo',
            field=models.URLField(null=True),
        ),
    ]
