# Generated by Django 4.2.4 on 2023-08-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_iconmain_header_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconmain',
            name='page_data',
        ),
        migrations.RemoveField(
            model_name='slidemain',
            name='page_data',
        ),
        migrations.AddField(
            model_name='iconmain',
            name='page_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='icon_slide', to='api.header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidemain',
            name='page_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_slide', to='api.header'),
            preserve_default=False,
        ),
    ]
