# Generated by Django 4.2.4 on 2023-09-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aboutas_feedback_feedbackpost_product_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, null=True)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
    ]
